services:
  mongodb:
    build: 
      context: .
      dockerfile: Dockerfile

    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - /usr/app:/data/db
    restart: always
  #   networks:
  #     - db-networks
  #     - mongo-tsapp-network 
  #   environment:
  #     MONGO_USERNAME: root
  #     MONGO_PASSWORD: rootpassword
  # networks:
  #   mongo-tsapp-network:
  #     external: true

  # networks:
  #   mongo-tsapp-network: